apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 503237308475.dkr.ecr.sa-east-1.amazonaws.com/eks-front
  newName: 503237308475.dkr.ecr.sa-east-1.amazonaws.com/eks-front
  newTag: 98bebed0
resources:
- ../../base
patchesStrategicMerge:
- fr-deploy-patch.yaml
- fr-service-patch.yaml
